import Head from "next/head";
import AllProducts from "../components/AllProducts";
import Link from "next/link";

export default function Home() {
  return (
    <div className="hoverflow-behavior-contain">
      <Head>
        <title>Comandee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className="text-center pt-4 text-green-700 font-bold text-4xl">
          Test
        </h1>

        <div className="pt-12 pb-9 max-w-xs mx-auto text-lg text-center space-y-6">
          <Link href={`/menus/A2PGPJB08CKXNJZSL0BBLHLX`} passHref>
            <a>GCR link example</a>
          </Link>
        </div>
      </div>
    </div>
  );
}
