import Head from "next/head";
import AllProducts from "../components/AllProducts";
import Link from "next/link";
import QRCode from "qrcode.react";

export default function Home() {
  return (
    <div className="hoverflow-behavior-contain">
      <Head>
        <title>Comandee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className="text-center pt-4 text-green-700 font-bold text-4xl">
          Landing
        </h1>

        <div className="pt-12 pb-9 max-w-xs mx-auto text-lg text-center space-y-6">
          <Link  href={`/examples/gcr`} passHref>
            <a className='btn bg-slate-800 text-white rounded-xl'>GCR example</a>
          </Link>
        </div>
       
      </div>
    </div>
  );
}
