import Head from "next/head";
import { fromImageToUrl, API_URL } from "../utils/urls";
// import Image from "next/image"; TODO
import Link from "next/link";

export default function Home({products}) {
  return (
    <div>
      <Head>
        <title>Comandee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-center pt-4 text-green-700 font-bold text-4xl">
          Products:
        </h1>

        <hr className="opacity-10 mt-6"/>

        <div className="pt-16 max-w-xs mx-auto text-lg space-y-8">
          {products.data.map((product) => (
            <div key={product.attributes.name}>
              <Link href={`/products/${product.attributes.slug}`} passHref>
                <a>
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={fromImageToUrl(product.attributes.image)}
                    alt="product image"
                    width={100}
                    height={100}
                  />

                  <div className="flex justify-between">
                    <p>{product.attributes.name}</p>
                    <p>
                      € {product.attributes.price.toFixed(2).replace(".", ",")}
                    </p>
                  </div>
                </a>
              </Link>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}


export async function getStaticProps() {
  //fetch products
  const products_res = await fetch(`${API_URL}/api/products?populate=image`)
  const products = await products_res.json()
  
  //return products
  return {
    props:{
      products
    }
  }
}