import Head from "next/head";
import { fromImageToUrl, API_URL } from "../utils/urls";
import Image from "next/image"; 
import Link from "next/link";

export default function Home({products}) {
  console.log(products.data)
  return (
    <div>
      <Head>
        <title>Comandee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-center pt-4 text-green-700 font-bold text-4xl">
          Menu:
        </h1>


        <div className="pt-12 pb-9 max-w-xs mx-auto text-lg space-y-6">
          {products.data.map((product) => (
            
            <div className="bg-gray-100 border border-slate-700 border-opacity-20 rounded-md py-1 px-2" key={product.attributes.name}>
              <Link href={`/products/${product.attributes.slug}`} passHref>
                <a>


                  <div className="flex justify-between space-x-2">
                    <div className="w-[120px] min-w-[120px]">
                      <Image
                        src={fromImageToUrl(product.attributes.image)}
                        alt="product image"
                        width="100%" height="100%" 
                        layout="responsive" 
                        objectFit="contain"
                        
                      />
                    </div>                    
                    <div className="text-right flex flex-col justify-between">
                      <p>{product.attributes.name}</p>
                      <p>
                        € {product.attributes.price.toFixed(2).replace(".", ",")}
                      </p>
                    </div>
                  </div>
                </a>
              </Link>
            </div>

          ))}
        </div>
      </main>
    </div>
  );
}


export async function getStaticProps() {
  //fetch products
  const products_res = await fetch(`${API_URL}/api/products?populate=image`)
  const products = await products_res.json()
  
  //return products
  return {
    props:{
      products
    },
    revalidate: 60,
  }
}