import Head from "next/head";
import Link from "next/link";
import QRCode from "qrcode.react";
import { useState } from "react";
import { MdArrowBack, MdArrowForward, MdClose } from "react-icons/md";
import ModalComponent from "../../components/ModalComponent";

const Gcr = () => {
  const [IsLoading, setIsLoading] = useState(false);
  return (
    <div className="mx-auto h-screen max-w-md ring-2 ring-gray-800">
      <Head>
        <title>Comandee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* ------ BODY ------- */}

      <div>
        <Link href={`/`} passHref>
          <a
            onClick={() => setIsLoading(true)}
            className={`btn btn-ghost rounded-xl  ${
              IsLoading ? "loading" : ""
            }`}
          >
            <MdArrowBack className="mr-1 text-2xl" />
            Indietro
          </a>
        </Link>

        <h1 className="pt-4 text-center text-4xl font-bold text-slate-700">
          Esempi
        </h1>

        <div className="mx-auto max-w-xs space-y-6 pt-12 pb-9 text-center text-lg">
          <ModalComponent
            btnText="esempio ristorante sushi"
            id="modal-sushi"
            btnIcon="🍣"
          >
            <h3 className="text-center text-lg font-bold">
              Menu per ristorante sushi
            </h3>

            <div className="my-10 w-full">
              <QRCode
                className="mx-auto"
                value="https://comandee-frontend.vercel.app/A2PGPJB08CKXNJZSL0BBLHLX/1"
              />
            </div>

            <div className="modal-action justify-between">
              <label htmlFor="modal-sushi" className="btn btn-error">
                chiudi
              </label>

              <Link href={`/A2PGPJB08CKXNJZSL0BBLHLX/1`} passHref>
                <a
                  onClick={() => setIsLoading(true)}
                  className={`btn rounded-xl bg-slate-800 text-white ${
                    IsLoading ? "loading" : ""
                  }`}
                >
                  Vai all&#39;esempio
                  <MdArrowForward className="ml-2 text-2xl" />
                </a>
              </Link>
            </div>
          </ModalComponent>

          <ModalComponent
            btnText="esempio ristorante di pesce"
            id="modal-pesce"
            btnIcon="🍲"
          >
            <h3 className="text-center text-lg font-bold">
              Menu per ristorante di pesce
            </h3>

            <div className="my-10 w-full">
              <QRCode
                className="mx-auto"
                value="https://comandee-frontend.vercel.app/8FVzKxJ84nYxW22N/0"
              />
            </div>

            <div className="modal-action justify-between">
              <label htmlFor="modal-pesce" className="btn btn-error">
                chiudi
              </label>

              <Link href={`/8FVzKxJ84nYxW22N/0`} passHref>
                <a
                  onClick={() => setIsLoading(true)}
                  className={`btn rounded-xl bg-slate-800 text-white ${
                    IsLoading ? "loading" : ""
                  }`}
                >
                  Vai all&#39;esempio
                  <MdArrowForward className="ml-2 text-2xl" />
                </a>
              </Link>
            </div>
          </ModalComponent>
        </div>
      </div>
    </div>
  );
};

export default Gcr;
