import Head from "next/head";
import Link from "next/link";
import QRCode from "qrcode.react";

const gcr = () => {
  return (
    <div className="hoverflow-behavior-contain">
      <Head>
        <title>Comandee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className="pt-4 text-center text-4xl font-bold text-green-700">
          Test
        </h1>

        <div className="mx-auto max-w-xs space-y-6 pt-12 pb-9 text-center text-lg">
          <Link href={`/A2PGPJB08CKXNJZSL0BBLHLX/1`} passHref>
            <a className="btn rounded-xl bg-slate-800 text-white">
              GCR link example
            </a>
          </Link>
        </div>
        <div className="mx-auto flex max-w-xs flex-col items-center space-y-4 text-center">
          <p>or scan the QR code:</p>

          <QRCode value="https://comandee-frontend.vercel.app/A2PGPJB08CKXNJZSL0BBLHLX/1" />
        </div>
      </div>
    </div>
  );
};

export default gcr;
