import Head from "next/head"
import Link from "next/link"
import QRCode from "qrcode.react"

const gcr = () => {
  return (
    <div className="hoverflow-behavior-contain">
      <Head>
        <title>Comandee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className="text-center pt-4 text-green-700 font-bold text-4xl">
          Test
        </h1>

        <div className="pt-12 pb-9 max-w-xs mx-auto text-lg text-center space-y-6">
          <Link  href={`/menus/A2PGPJB08CKXNJZSL0BBLHLX`} passHref>
            <a className='btn bg-slate-800 text-white rounded-xl'>GCR link example</a>
          </Link>
        </div>
        <div className="flex flex-col items-center max-w-xs mx-auto space-y-4 text-center">
          <p>or scan the QR code:</p>

          <QRCode value="https://comandee-frontend.vercel.app/menus/A2PGPJB08CKXNJZSL0BBLHLX" />
        </div>
      </div>
    </div>
  )
}

export default gcr