import Head from "next/head";
import React, { useContext, useEffect } from "react";
import { API_URL } from "../../../utils/urls";
import AllProducts from "../../components/AllProducts";
import { useRouter } from "next/router";
import MenusLayout from "../../shared/MenusLayout";
import MenuContext from "../../state/MenuContext";

export default function UserId({ Menus }) {
  const router = useRouter();
  const menus = Menus.data[0].attributes.menus.data;
  const cenaCategories = menus[1].attributes.categories.data;
  const { MenuState, setMenuState } = useContext(MenuContext);

  useEffect(() => {
    if (MenuState.Loaded) {
      return;
    } else {
      const drawerData = [];
      cenaCategories.forEach((e) =>
        drawerData.push({
          title: e.attributes.name,
          to: e.attributes.slug,
        })
      );
      setMenuState({
        Loaded: true,
        data: drawerData,
      });
    }
  }, [MenuState.Loaded, cenaCategories, setMenuState]);

  return (
    <div className="hoverflow-behavior-contain">
      <Head>
        <title>Comandee</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MenusLayout>
        <div className="space-y-4 text-center">
          <h1 className=" text-4xl font-bold text-green-700">
            Menu {menus[1].attributes.name}:
          </h1>

          <p className="text-xl font-medium">
            {menus[1].attributes?.menuDescription.split("_")[0]}
          </p>

          <div className="space-y-1">
            <p className="text-sm">
              {menus[1].attributes?.menuDescription.split("_")[1]}
            </p>
            <p className="text-sm">
              {menus[1].attributes?.menuDescription.split("_")[2]}
            </p>
          </div>
        </div>

        <div className="mx-auto max-w-xs space-y-6 pt-8 pb-9 text-lg">
          {cenaCategories.map((category) => (
            <div key={category.attributes.slug}>
              <h3
                className="text-center text-xl font-medium text-rose-700"
                id={category.attributes.slug}
              >
                {category.attributes.name}
              </h3>
              <AllProducts
                UserId={router.query.UserId}
                products={category.attributes.products.data}
              />
            </div>
          ))}
        </div>
      </MenusLayout>
    </div>
  );
}

export async function getStaticPaths() {
  try {
    //retrieve all the possible paths
    const users_res = await fetch(`${API_URL}/api/user-ids`);
    const users = await users_res.json();
    //return them to NextJs app
    return {
      paths: users.data.map((user) => ({
        params: { UserId: String(user.attributes.uid) },
      })),
      fallback: false,
    };
  } catch (error) {
    console.log(error);
    return null;
  }
}

export async function getStaticProps({ params: { UserId } }) {
  //fetch products
  // const products_res = await fetch(`${API_URL}/api/products?populate=image`)
  //const products = await products_res.json()
  const Menus_res = await fetch(
    `${API_URL}/api/user-ids?populate[menus][populate][categories][populate][products][populate]=image&filters[uid][$eq]=${UserId}`
  );
  const Menus = await Menus_res.json();

  return {
    props: {
      Menus,
    },
    revalidate: 60,
  };
}
